version: "3"
services:
  mysql:
    image: wrfly/brute_force-mongodb:latest
    ports:
      - 27017
    environment:
      - FLAG=<FLAG>
    deploy:
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.05'
          memory: 50M
        reservations:
          cpus: '0.001'
          memory: 30M
    healthcheck:
      test: ["CMD", "pgrep", "mongod"]
      interval: 20s
      timeout: 1s
      retries: 2