version: "3"
services:
  nginx:
    image: wrfly/brute-force_post-form:latest
    environment:
      - FLAG=<FLAG>
    ports:
      - 80
    deploy:
      placement:
        constraints:
          - node.role != manager
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.05' # CPU Limit 5%
          memory: 25M  # Mem Limit 25M
        reservations:
          cpus: '0.001'
          memory: 15M